### ISSUE TITLE
(Flutter beta) NoSuchMethodError: The getter 'hasFloatingPlaceholder was called on null.

### ISSUE THREAD

**Issue by kubastick** [psovit/rich_code_editor#11]
```The getter 'hasFloatingPlaceholder' was called on null.
I/flutter (30091): Receiver: null
I/flutter (30091): Tried calling: hasFloatingPlaceholder
I/flutter (30091): 
I/flutter (30091): User-created ancestor of the error-causing widget was:
I/flutter (30091):   CodeTextField
I/flutter (30091): 
I/flutter (30091): When the exception was thrown, this was the stack:
I/flutter (30091): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (30091): #1      _InputDecoratorState.initState (package:flutter/src/material/input_decorator.dart:1851:33)
I/flutter (30091): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4060:58)
I/flutter (30091): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
I/flutter (30091): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
I/flutter (30091): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
...

```

Flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.8.3, on Microsoft Windows [Version 10.0.18362.295], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.4)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by psovit** [comment]
@kubastick do you get the above error on compile time itself or when you try to use the `CodeTextField`? if the error is thrown during usage, can you please share the code you have used?

**Comment by psovit** [comment]
Closing due to lack of activity. Also, the previous implementation have significantly changed as of v1.0.0
