### ISSUE TITLE
support desktop request

### ISSUE THREAD

**Issue by kanam999** [psovit/rich_code_editor#8]
Thank you for developing this.
It would be nice to support desktop as well.

**Comment by psovit** [comment]
@kanam999 i haven't worked with Flutter for web/desktop yet. Only been working with Flutter for mobile. I am not sure if I will have time to look into desktop anytime soon.
If you are interested, please feel free to try the desktop and contribute.
Thanks!

**Comment by MichelDiz** [comment]
I was about to try on desktop, but I got:
```
Syncing files to device macOS...                                        
                                                                
Compiler message:
Syncing files to device macOS...                                                   ../../../.pub-cache/hosted/pub.dartlang.org/rich_code_editor-0.2.9/lib/code_editor/
widgets/code_editable_text.dart:1388:11: Error: The getter 'kMinInteractiveSize'
isn't defined for the class 'CodeEditableTextState'.
Syncing files to device macOS...                                                    - 'CodeEditableTextState' is from                              
 'package:rich_code_editor/code_editor/widgets/code_editable_text.dart'
 ('../../../.pub-cache/hosted/pub.dartlang.org/rich_code_editor-0.2.9/lib/code_edit
 or/widgets/code_editable_text.dart').
Syncing files to device macOS...                                                   Try correcting the name to the name of an existing getter, or defining a getter or
field named 'kMinInteractiveSize'.
Syncing files to device macOS...                                                             kMinInteractiveSize,                                  
Syncing files to device macOS...                                                             ^^^^^^^^^^^^^^^^^^^                                   
Syncing files to device macOS...                                                    4.517ms (!)                                       
error Command failed with exit code 3.
```

Which is the same issue in https://github.com/psovit/rich_code_editor/issues/13

**Comment by psovit** [comment]
@MichelDiz the library has now been updated to work with Flutter 1.12.13+hotfix.7.

**Comment by BasedMusa** [comment]
I tried it for my personal productivity toolkit, here's what I got:

**VERSION**
`rich_code_editor: 0.4.1`

**LOGS**
```
Performing hot reload...
Syncing files to device macOS...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building CodeTextField(controller: CodeEditingController#33e3c(CodeEditingValue(text: ┤├, selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))), decoration: InputDecoration(hintText: "Enter Your Code Here", floatingLabelBehavior: FloatingLabelBehavior.auto), keyboardType: TextInputType(name: TextInputType.emailAddress, signed: null, decimal: null), style: TextStyle(inherit: true, color: Color(0xff000000), size: 16.0), autofocus: true, maxLines: 150, minLines: 50, textInputAction: newline, dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#347b0]], state: CodeTextFieldState#99229):
'package:rich_code_editor/code_editor/widgets/code_editable_text.dart': Failed assertion: line 328 pos 16: 'cursorColor != null': is not true.

The relevant error-causing widget was: 
  CodeTextField file:///Users/musa/Work/based_kit/lib/widgets/new_snippet_dialog.dart:101:34
When the exception was thrown, this was the stack: 
#2      new CodeEditableText (package:rich_code_editor/code_editor/widgets/code_editable_text.dart:328:16)
#3      CodeTextFieldState.build (package:rich_code_editor/code_editor/widgets/code_text_field.dart:961:14)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 5 of 734 libraries in 436ms.

```

**MY CODE**
```Dart
                         CodeTextField(
                            controller: _codeController,
                            keyboardType: TextInputType.emailAddress,
                            textInputAction: TextInputAction.newline,
                            highlighter: DummyHighlighter(),
                            onChanged: _onCodeChanged,
                            minLines: 50,
                            maxLines: 150,
                            autofocus: true,
                            style:
                                TextStyle(fontSize: 16.0, color: Colors.black),
                            decoration: InputDecoration(
                              hintText: "Enter Your Code Here",
                            ),
                          ),
```

**Is the `cursorColor` variable suppose to be null by default?**

**Comment by BasedMusa** [comment]
I tried version: `0.4.0` but that one just has a hell load of unstability. And feels unresponsive, the best way to make it feel more realistic and to improve the UX would be to implement Key listening for buttons such as "SPACE", or "ENTER".

**Comment by psovit** [comment]
@BasedMusa sorry for late response. i have modified the library quite bit as of now. please check out v1.0.0 which is the most stable release.
